version: "3"
services:
  apm-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
    - 9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      ELASTICSEARCH_URL: http://apm-elasticsearch:9200
    ports:
    - 5601:5601
    links:
    - apm-elasticsearch
    depends_on:
    - apm-elasticsearch
  elastic-apm-server:
    image: docker.elastic.co/apm/apm-server:6.5.0
    command: [
      "bash",
      "-c",
      "apm-server run -e -E
                          output.elasticsearch.hosts=['http://apm-elasticsearch:9200']
                          "]
    ports:
    - 8200
    links:
    - apm-elasticsearch
    depends_on:
    - apm-elasticsearch
  order-service:
    image: docker.io/devbhuwan/order-service
    build:
      context: order-service
      dockerfile: Dockerfile
      args:
      - JAR_FILE=target/order-service-1.0-SNAPSHOT.jar
    ports:
    - 8080:8080
    environment:
      ELASTIC_APM_SERVICE_NAME: order-service
      ELASTIC_APM_APPLICATION_PACKAGES: io.github.bhuwanupadhyay
      ELASTIC_APM_SERVER_URLS: http://elastic-apm-server:8200
    links:
    - elastic-apm-server
    depends_on:
    - elastic-apm-server
